# Configurando github actions
# https://github.com/peter-evans/docker-compose-actions-workflow
# https://stackoverflow.com/questions/51968779/error-define-and-run-multi-container-applications-with-docker
# https://docs.github.com/es/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action

name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #docker-compose build
    #docker-compose up
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: Run docker compose
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
